---


- name: Oracle dependences with Redhat install
  shell: "{{ role_path }}/files/prepare_redhat_repo.sh"

- name: Oracle host config
  shell: "{{ role_path }}/files/change_host.sh"

- name: Oracle copy config
  template: src=db_install.rsp.j2 dest=/tmp/db_install.rsp

- name: Oracle installation
  shell: "{{ role_path }}/files/install.sh"

- name: Oracle render dbca config
  template: src=dbca.rsp.j2 dest=/tmp/dbca.rsp

- name: Oracle init database
  shell: "{{ role_path }}/files/database_initialize.sh"
